### ISSUE TITLE
Thank you for this excellent project. I am a newbie and encountered the following error when running according to the instructions:

### ISSUE THREAD

**Issue by xdgene** [felicity-health/felicity-lims#22]

**Comment by xdgene** [comment]
Thank you for this excellent project. I am a newbie and encountered the following error when running according to the instructions: 
 File "/data1/zhanglin/lims/felicity/backend/felicity_lims/felicity/api/rest/api_v1/api.py", line 3, in <module>
    from felicity.api.rest.api_v1.fhir import r4
  File "/data1/zhanglin/lims/felicity/backend/felicity_lims/felicity/api/rest/api_v1/fhir/r4.py", line 4, in <module>
    from felicity.apps.iol.fhir.schema import PatientResource, ServiceRequestResource, DiagnosticReportResource
  File "/data1/zhanglin/lims/felicity/backend/felicity_lims/felicity/apps/iol/fhir/schema.py", line 6, in <module>
    class Coding(BaseModel):
  File "/data1/zhanglin/lims/felicity/backend/felicity_lims/felicity/apps/iol/fhir/schema.py", line 8, in Coding
    system: str | None = None
TypeError: unsupported operand type(s) for |: 'type' and 'NoneType'
[2023-02-21 17:21:06 +0800] [10724] [INFO] Worker exiting (pid: 10724)
[2023-02-21 17:21:07 +0800] [10707] [INFO] Shutting down: Master
[2023-02-21 17:21:07 +0800] [10707] [INFO] Reason: Worker failed to boot.
some suggestion？ thank you very much！

**Comment by aurthurm** [comment]
hie @xdgene can you be a bit specific.
1. Which instructions did you follow,
2.  Can you provice the full error log


Suggestion:
conda create -n felicity python=3.9
conda activate felicity
git clone https://github.com/aurthurm/felicity.git
cd felicity
cd backend/felicity_lims
pip install -r requirements.txt
cd backend/felicity/felicity_lims
bash ./al_upgrade.sh
bash ./runuvicorn.sh

Then do this section Frontend Installation

avoid the docker setup for now. I have done some breaking changes there

**Comment by aurthurm** [comment]
@xdgene you can use docker now with

```
docker-compose -f dc.nginx.dev.yaml up --b
```
Then access the site at `http://localhost/`

**Comment by xdgene** [comment]
> 

I have tried using both Docker and Conda separately, but neither worked. 

here's docker error
docker-compose -f dc.nginx.dev.yaml up --b
error:
...
felicity_fe exited with code 1
felicity_fe       | 
felicity_fe       | > felicity-lims@0.1.0 dev /app/vite
felicity_fe       | > vite "--host" "--port" "3000"
felicity_fe       | 
felicity_fe       | sh: 1: vite: not found
felicity_fe       |  ELIFECYCLE  Command failed.
felicity_fe exited with code 1
felicity_fe       | 
felicity_fe       | > felicity-lims@0.1.0 dev /app/vite
felicity_fe       | > vite "--host" "--port" "3000"
felicity_fe       | 
felicity_fe       | sh: 1: vite: not found
felicity_fe       |  ELIFECYCLE  Command failed.
felicity_fe       |  WARN   Local package.json exists, but node_modules missing, did you mean to install?
felicity_fe exited with code 1
felicity_fe       | 
felicity_fe       | > felicity-lims@0.1.0 dev /app/vite
felicity_fe       | > vite "--host" "--port" "3000"
felicity_fe       | 
felicity_fe       | sh: 1: vite: not found
felicity_fe       |  ELIFECYCLE  Command failed.
felicity_fe       |  WARN   Local package.json exists, but node_modules missing, did you mean to install?
felicity_fe exited with code 1
felicity_fe       | 
felicity_fe       | > felicity-lims@0.1.0 dev /app/vite
felicity_fe       | > vite "--host" "--port" "3000"
felicity_fe       | 
felicity_fe       | sh: 1: vite: not found
felicity_fe       |  ELIFECYCLE  Command failed.
felicity_fe       |  WARN   Local package.json exists, but node_modules missing, did you mean to install?
felicity_fe exited with code 1


Perhaps I need to learn more basic knowledge.thanks again！
